# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: IAC_Agents

steps:
- task: PowerShell@2
  inputs:
    filePath: '$(Build.Repository.LocalPath)\build.ps1'
  displayName: Build

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)\*.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'